; This file both activates and configures xdebug; the .so is only
; present in dev images (copied from the build-dev stage).
zend_extension=xdebug

xdebug.mode=debug
xdebug.start_with_request=yes
xdebug.client_host=host.docker.internal
xdebug.client_port=9003
